# Generated by Django 4.1.13 on 2024-03-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_remove_paid_course_content_selected_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='Course_PName',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paid_course_content',
            name='Course_Name_FK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.coursecontent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='particularcourse',
            name='Course_video_identifier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='Course_purchased',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paid_course_content',
            name='Select',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Dot_net', 'Dot_net'), ('Javascript', 'Javascript')], max_length=20),
        ),
    ]
