# Generated by Django 4.1.13 on 2024-03-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_remove_paid_course_content_course_fkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_course_content',
            name='Course_FKey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.coursecontent'),
            preserve_default=False,
        ),
    ]
