# Generated by Django 4.1.13 on 2024-03-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_paid_course_content_course_fkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_course_content',
            name='Select',
        ),
    ]
