# Generated by Django 4.1.13 on 2024-03-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_alter_paid_course_content_course_fkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_course_content',
            name='Course_FKey',
        ),
        migrations.AddField(
            model_name='paid_course_content',
            name='Course_Heading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.demo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paid_course_content',
            name='Course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.coursecontent'),
            preserve_default=False,
        ),
    ]
